// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommunicationMessageType.proto

package ProtoMessages;

public final class CommunicationMessageTypeBase {
  private CommunicationMessageTypeBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code eCommunicationMessageType}
   */
  public enum eCommunicationMessageType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>cmtNone = 0;</code>
     */
    cmtNone(0, 0),
    /**
     * <code>cmtPing = 1;</code>
     *
     * <pre>
     * simple message that send client to server
     * </pre>
     */
    cmtPing(1, 1),
    /**
     * <code>cmtPong = 2;</code>
     *
     * <pre>
     * simple message that send server to client
     * </pre>
     */
    cmtPong(2, 2),
    ;

    /**
     * <code>cmtNone = 0;</code>
     */
    public static final int cmtNone_VALUE = 0;
    /**
     * <code>cmtPing = 1;</code>
     *
     * <pre>
     * simple message that send client to server
     * </pre>
     */
    public static final int cmtPing_VALUE = 1;
    /**
     * <code>cmtPong = 2;</code>
     *
     * <pre>
     * simple message that send server to client
     * </pre>
     */
    public static final int cmtPong_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    public static eCommunicationMessageType valueOf(int value) {
      switch (value) {
        case 0: return cmtNone;
        case 1: return cmtPing;
        case 2: return cmtPong;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<eCommunicationMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<eCommunicationMessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<eCommunicationMessageType>() {
            public eCommunicationMessageType findValueByNumber(int number) {
              return eCommunicationMessageType.valueOf(number);
            }
          };

    private final int value;

    private eCommunicationMessageType(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:eCommunicationMessageType)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
