// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommunicationMessageType.proto

#ifndef PROTOBUF_CommunicationMessageType_2eproto__INCLUDED
#define PROTOBUF_CommunicationMessageType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_CommunicationMessageType_2eproto();
void protobuf_AssignDesc_CommunicationMessageType_2eproto();
void protobuf_ShutdownFile_CommunicationMessageType_2eproto();


enum eCommunicationMessageType {
  cmtNone = 0,
  cmtPing = 1,
  cmtPong = 2
};
bool eCommunicationMessageType_IsValid(int value);
const eCommunicationMessageType eCommunicationMessageType_MIN = cmtNone;
const eCommunicationMessageType eCommunicationMessageType_MAX = cmtPong;
const int eCommunicationMessageType_ARRAYSIZE = eCommunicationMessageType_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::eCommunicationMessageType> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CommunicationMessageType_2eproto__INCLUDED
