// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponsePong.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageResponsePong.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageResponsePong_2eproto() {
  delete MessageResponsePong::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageResponsePong_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageResponsePong_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  MessageResponsePong::default_instance_ = new MessageResponsePong();
  MessageResponsePong::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageResponsePong_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageResponsePong_2eproto_once_);
void protobuf_AddDesc_MessageResponsePong_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageResponsePong_2eproto_once_,
                 &protobuf_AddDesc_MessageResponsePong_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageResponsePong_2eproto {
  StaticDescriptorInitializer_MessageResponsePong_2eproto() {
    protobuf_AddDesc_MessageResponsePong_2eproto();
  }
} static_descriptor_initializer_MessageResponsePong_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int MessageResponsePong::kSomeTextFieldNumber;
#endif  // !_MSC_VER

MessageResponsePong::MessageResponsePong()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageResponsePong)
}

void MessageResponsePong::InitAsDefaultInstance() {
}

MessageResponsePong::MessageResponsePong(const MessageResponsePong& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageResponsePong)
}

void MessageResponsePong::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  sometext_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageResponsePong::~MessageResponsePong() {
  // @@protoc_insertion_point(destructor:MessageResponsePong)
  SharedDtor();
}

void MessageResponsePong::SharedDtor() {
  sometext_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MessageResponsePong::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageResponsePong& MessageResponsePong::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageResponsePong_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageResponsePong_2eproto();
#endif
  return *default_instance_;
}

MessageResponsePong* MessageResponsePong::default_instance_ = NULL;

MessageResponsePong* MessageResponsePong::New(::google::protobuf::Arena* arena) const {
  MessageResponsePong* n = new MessageResponsePong;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageResponsePong::Clear() {
  if (has_sometext()) {
    sometext_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool MessageResponsePong::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:MessageResponsePong)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string someText = 1 [default = ""];
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sometext()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageResponsePong)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageResponsePong)
  return false;
#undef DO_
}

void MessageResponsePong::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageResponsePong)
  // required string someText = 1 [default = ""];
  if (has_sometext()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->sometext(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:MessageResponsePong)
}

int MessageResponsePong::ByteSize() const {
  int total_size = 0;

  // required string someText = 1 [default = ""];
  if (has_sometext()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sometext());
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageResponsePong::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageResponsePong*>(&from));
}

void MessageResponsePong::MergeFrom(const MessageResponsePong& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_sometext()) {
      set_has_sometext();
      sometext_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sometext_);
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void MessageResponsePong::CopyFrom(const MessageResponsePong& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageResponsePong::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MessageResponsePong::Swap(MessageResponsePong* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageResponsePong::InternalSwap(MessageResponsePong* other) {
  sometext_.Swap(&other->sometext_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.swap(other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageResponsePong::GetTypeName() const {
  return "MessageResponsePong";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponsePong

// required string someText = 1 [default = ""];
bool MessageResponsePong::has_sometext() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageResponsePong::set_has_sometext() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageResponsePong::clear_has_sometext() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageResponsePong::clear_sometext() {
  sometext_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sometext();
}
 const ::std::string& MessageResponsePong::sometext() const {
  // @@protoc_insertion_point(field_get:MessageResponsePong.someText)
  return sometext_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponsePong::set_sometext(const ::std::string& value) {
  set_has_sometext();
  sometext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageResponsePong.someText)
}
 void MessageResponsePong::set_sometext(const char* value) {
  set_has_sometext();
  sometext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageResponsePong.someText)
}
 void MessageResponsePong::set_sometext(const char* value, size_t size) {
  set_has_sometext();
  sometext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageResponsePong.someText)
}
 ::std::string* MessageResponsePong::mutable_sometext() {
  set_has_sometext();
  // @@protoc_insertion_point(field_mutable:MessageResponsePong.someText)
  return sometext_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MessageResponsePong::release_sometext() {
  clear_has_sometext();
  return sometext_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponsePong::set_allocated_sometext(::std::string* sometext) {
  if (sometext != NULL) {
    set_has_sometext();
  } else {
    clear_has_sometext();
  }
  sometext_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sometext);
  // @@protoc_insertion_point(field_set_allocated:MessageResponsePong.someText)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
